export const NUMBER_OF_CARDS_ON_REGULAR_SCREEN = 12;
export const NUMBER_OF_CARDS_ON_MIDDLE_SCREEN = 8; 
export const NUMBER_OF_CARDS_ON_SMALL_SCREEN = 5;
export const NUMBER_OF_CARDS_ON_FULL_SCREEN_LOAD_MORE = 3;
export const NUMBER_OF_CARDS_ON_REGULAR_SCREEN_LOAD_MORE = 2;
